#!/bin/bash
#
# Wrapper to encrypt all secret files
# Platform: Unix
#
# Author:   Dmitriy Ivanov
#

# Environment
ANSIBLE_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Script
while read -u 5 line; do
	${ANSIBLE_HOME}/av encrypt ${line}
done 5<.enc

