---
- name: User's environment and software
  hosts: arch
  gather_facts: true
  roles:
    - role: soft
      tags: ["user_env", "soft"]
      become: true

    - role: touchpad
      tags: ["hardware", "touchpad"]
      become: true

    - role: services
      tags: ["systemd", "services"]
      become: true

