---
- hosts: localhost
  become: true
  roles:
    - { role: system, tags: ['system'] }
    # - { role: aura,   tags: ['aura']   }
    # - { role: user,   tags: ['user']   }
  vars:
    user_name:  divanov
    system_hostname: divanov-dev