---
- hosts: localhost
  become: true
  roles:
    ## System
    # - { role: aur_tools,    tags: ['aur_tools','aura', 'aur' ]      }
    # - { role: user,         tags: ['user']                          }
    - { role: system,         tags: ['system']                        }
    # - { role: xorg,         tags: ['xorg']                          }
    - { role: virtualbox,     tags: ['virtualbox']                    }
    - { role: kvm,            tags: ['kvm']                           }
    - { role: docker,         tags: ['docker']                        }

    ## Desktop
    - { role: desktop,        tags: ['desktop']                       }
    - { role: browsers,       tags: ['browsers']                      }
    - { role: office,         tags: ['office']                        }

    ## Development
    - { role: dev_tools,      tags: ['dev_tools', 'tools']            }
    - { role: dev_cpp,        tags: ['dev_cpp', 'cpp']                }
    - { role: dev_javascript, tags: ['dev_javascript', 'javascript']  }
    - { role: dev_java,       tags: ['dev_java', 'java']              }
    - { role: dev_python,     tags: ['dev_python', 'python']          }
    - { role: dev_haskell,    tags: ['dev_haskell', 'haskell']        }
    - { role: dev_go,         tags: ['dev_go', 'go']                  }
    - { role: dev_dotnet,     tags: ['dev_dotnet', 'dotnet']          }

  vars:
    user_name:  divanov
    system_hostname: divanov-dev
