---
- name: User's environment and software
  hosts: all
  gather_facts: true

  vars:
    services: "{{ ansible_os_family }}_services"
  
  vars_prompt:
  - name: "need_main_software_setup"
    prompt: "Do you want to install main software packages? (yes/no)"
    default: "no"
    private: no
    
  - name: "need_aur_init"
    prompt: "[ARCHLINUX ONLY] Do you want to install AUR installer Yaourt? (yes/no)"
    default: "no"
    private: no

  - name: "need_aur_software_setup"
    prompt: "[ARCHLINUX ONLY] Do you want to install AUR software packages? (yes/no)"
    default: "no"
    private: no

  roles:
    # --- Workstation environment ---
    - role: base
      tags: ["base"]
      become: true

    # --- Laptop environment ---
    - role: laptop
      tags: ["hardware", "laptop"]
      become: true
      when: laptop == "yes"

    # --- Workstation environment ---
    - role: userspace
      tags: ["user_env", "userspace"]
      become: true
      when: need_user_environment == "yes"

- name: Oracle database
  hosts: oracle
  gather_facts: true

  roles:
    - role: oracle
      tags: ["oracle"]
