---

- name: Create group {{ user_name }}
  group:
    name: "{{ user_name }}"

- name: Create user {{ user_name }} in wheel group
  user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    groups: wheel
    password: "{{ user_encrypted_password }}"
    update_password: on_create
    createhome: yes

- name: Install bash and bash-completion to be set as preferred shell.
  package:
    name: 
      - bash
      - bash-completion

- name: Set preferred shell for {{ user_name }}
  user:
    name: "{{ user_name }}"
    shell: /bin/bash

- name: Create workspace folders
  file:
    path: /home/{{ user_name }}/{{ item }}
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    state: directory
  with_items:
     - "workspace/backup"
     - "workspace/libs"
     - "workspace/misc"
     - "workspace/my"
     - "workspace/test"
     - "workspace/tmp"
