---

- name: Install cloud untilities
  pacman:
    name:
      - aws-cli
      - terraform
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install cloud untilities (AUR)
  aura:
    name:
      - awless
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
