---
services:
  - "acpid.service"
  - "avahi-daemon.service"
  - "cpupower.service"
  - "cronie.service"
  - "cups-browsed"
  - "docker.service"
  - "dhcpcd"
  # - "fancontrol.service"
  - "healthd.service"
  - "irqbalance.service"
  - "libvirtd.service"
  - "lightdm.service"
  - "lm_sensors.service"
  - "NetworkManager.service"
  # - "NetworkManager-dispatcher"
  #- "samba.service"
  - "sshd.service"
  - "supervisord.service"
  - "sysstat.service"
  - "systemd-timesyncd.service"
  # - "teamviewerd.service" # Not So Simple
  - "thermald.service"
  - "wpa_supplicant.service"
