---

- name: Install grub and efiamanager
  pacman:
    name:
      - grub
      - efibootmgr

- name: Install GRUB configuration
  copy:
    src: etc/default/grub
    dest: /etc/default/grub
  notify:
    - build grub config