---

- name: Uninstall ntfs-3g base package
  pacman:
    name: ntfs-3g
    state: absent
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install ntfs-3g-fuse to allow normal users to mount NTFS Volumes.
  aura:
    name: ntfs-3g-fuse
    # user: "{{ user_name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
