---

- name: Install linux kernel
  pacman:
    name:
      - linux
      - linux-headers
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install mkinitcpio and presets
  pacman:
    name:
      - linux
      - mkinitcpio
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - create init ramdisk

- name: Install firmare
  pacman:
    name: 
      - linux-firmware
      - intel-ucode
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  notify:
    - create init ramdisk

- name: Install mkinitcpio configuration
  copy:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
  notify:
    - create init ramdisk
