---

- name: Install linux kernel
  pacman:
    name:
      - linux
      - linux-headers

- name: Install mkinitcpio and presets
  pacman:
    name:
      - linux
      - mkinitcpio
  notify:
    - create init ramdisk

- name: Install firmare
  pacman:
    name: 
      - linux-firmware
      - intel-ucode
  notify:
    - create init ramdisk

- name: Install mkinitcpio configuration
  copy:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
  notify:
    - create init ramdisk
