---

- name: Upgrade Arch Linux
  pacman:
    update_cache: yes
    upgrade: yes

- name: Give wheel group sudo (with password) privileges
  lineinfile:
    dest: /etc/sudoers
    line: "%wheel ALL=(ALL) ALL"
    state: present
    validate: 'visudo -cf %s'

- name: Install inetutils
  pacman:
    name: inetutils

- name: Set hostname to {{ system_hostname }}
  hostname:
    name: "{{ system_hostname }}"
  # hostnamectl doesn't work properly in a container (which is used for testing)
  # See https://lists.freedesktop.org/archives/systemd-devel/2017-February/038291.html
  when: lookup('env', 'container') != 'docker'

- name: Set timezone to {{ system_timezone }}
  timezone:
    name: "{{ system_timezone }}"

- name: Set locale to {{ system_locale }}
  locale_gen:
    name: "{{ system_locale }}"

- name: Install linux kernel
  pacman:
    name:
      - linux
      - linux-headers

- name: Install mkinitcpio and presets
  pacman:
    name:
      - linux
      - mkinitcpio

- name: Install mkinitcpio configuration
  copy:
    src: mkinitcpio.conf
    dest: /etc/mkinitcpio.conf
  notify:
    - Create initial ramdisk environment

- name: Install pacman.conf
  file:
    path: etc/pacman.conf
    dest: /etc/pacman.conf

- name: Install sound utilities
  pacman:
    name: alsa-utils

- name: Install openssh
  pacman:
    name: openssh

- name: Install firmare
  pacman:
    name: linux-firmware
