---

- name: Install Java
  pacman:
    name:
      - jdk-openjdk   # Latest 13
      - jdk8-openjdk
      - jdk11-openjdk

- name: Install Oracle Java
  pacman:
    name:
      - jdk   # Latest 14
      - jdk8
      - jdk11

- name: Install common Java build tools
  pacman:
    name:
      - ant
      - bazel
      - gradle
      - maven

- name: Install Decompilers
  aura:
    name:
      - jd-gui

# See https://confluence.jetbrains.com/display/IDEADEV/Inotify+Watches+Limit
- name: Set inotify watches limit to {{ inotify_max_user_watches }}
  lineinfile:
    path: /etc/sysctl.d/idea.conf
    regexp: "^fs.inotify.max_user_watches.*"
    line: "fs.inotify.max_user_watches = {{ inotify_max_user_watches }}"
    create: yes
