---

- name: Install docker
  pacman:
    name:
      - docker
      - docker-compose
      - docker-machine
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Install container tools (AUR)
  aura:
    name:
      - ctop
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Enable and start libvirtd service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user {{ user_name }} in docker group
  user:
    name: "{{ user_name }}"
    groups: docker
    append: yes
