---
- name: Copy touchpad description to xorg.conf.d
  copy:
    src: "files/{{item}}"
    dest: "/etc/X11/xorg.conf.d/{{item}}"
    owner: "{{root_user}}"
    group: "{{root_group}}"
    mode: '0644'
  with_items:
    - 70-synaptics.conf
  
- name: Disable touchpad when mouse existed
  template: src=01-touchpad.rules.j2 dest=/etc/udev/rules.d/01-touchpad.rules
  