---
# ********************* Services
- name: Cron default config 
  copy: src=etc/default/cron dest=/etc/default/cron
  tags: [config]
  notify: restart cron

- name: IRQBalance default config
  copy: src=etc/default/irqbalance dest=/etc/default/irqbalance
  tags: [config]
  notify: restart irqbalance

- name: '[Archlinux] Start and Enable services'
  service:
    name: "{{item}}"
    state: "started"
    enabled: "yes"
  with_items:
    - "{{ Archlilnux_services }}"
  when: 
    - ansible_os_family == "Archlinux"

- name: '[Gentoo] Start and Enable servicess'
  service:
    name: "{{item}}"
    state: "started"
    enabled: "yes"
  with_items:
    - "{{ Gentoo_services }}"
  when: 
    - ansible_os_family == "Gentoo"

- name: '[RedHat] Start and Enable services'
  service:
    name: "{{item}}"
    state: "started"
    enabled: "yes"
  with_items:
    - "{{ RedHat_services }}"
  when: 
    - ansible_os_family == "RedHat"
