---
# Installation of Maintained packages

# ********************* ArchLinux
- name: Install software on Arch Linux
  include: pacman.yml
  when: 
    - ansible_os_family == "Archlinux"
    - ansible_pkg_mgr == "pacman"
    - need_main_software_setup == "yes"


- name: Add keys for AUR packages
  command: "gpg --keyserver {{ item.keyserver }} --recv-keys {{ item.key }}"
  become: false
  with_items: "{{ gpg_keys }}"
  when: 
    - ansible_os_family == "Archlinux"
    - ansible_pkg_mgr == "pacman"

# Installation of Community packages
- name: Install initial AUR packages
  include: aur_makepkg.yml pkg_name={{item}}
  when: 
    - ansible_os_family == "Archlinux"
    - need_aur_init == "yes"
  with_items:
    - "{{ aur_packages_init }}"

- name: Install main AUR packages
  command: "yaourt -S --noconfirm {{item}}"
  become: false
  when:
    - ansible_os_family == "Archlinux"
    - need_aur_software_setup == "yes"
  with_items:
    - "{{ aur_packages }}"

# ********************* Gentoo
- name: Install software on Arch Linux
  include: portage.yml
  when: 
    - ansible_os_family == "Gentoo"
    - ansible_pkg_mgr == "portage"
    - need_main_software_setup == "yes"

# ********************* Dev RHEL
- name: Install software on Arch Linux
  include: yum_common.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_pkg_mgr == "yum"
    - need_main_software_setup == "yes"

# ********************* Dev Oracle


# ********************* Dev Stronghold


# ********************* Common
- name: Install pip packages
  pip: name={{ item }} state=present
  when: need_main_software_setup == "yes"
  with_items:
    - "{{ pip_packages }}"
