---
- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
    update_cache: yes
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  become: true

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  become: true

- name: Software installation
  yum: name={{ item }} state=present
  with_items:
    - "{{ common_packages}}"
  become: true