---
- name: Install software on Arch Linux
  include: pacman.yml
  when: 
    - ansible_os_family == "Archlinux"
    - ansible_pkg_mgr == "pacman"

- name: Install pip packages
  pip: name={{ item }} state=present
  with_items:
    - "{{ pip_packages }}"