---
# Installation of Maintained packages
- name: Install software on Arch Linux
  include: pacman.yml
  when: 
    - ansible_os_family == "Archlinux"
    - ansible_pkg_mgr == "pacman"

- name: Install pip packages
  pip: name={{ item }} state=present
  when: need_main_software_setup == "yes"
  with_items:
    - "{{ pip_packages }}"

# Installation of Community packages
- name: Install initial AUR packages
  include: aur_makepkg.yml pkg_name={{item}}
  when: 
    - ansible_os_family == "Archlinux"
    - need_aur_init == "yes"
  with_items:
    - "{{ aur_packages_init }}"

- name: Install main AUR packages
  command: "yaourt -S --noconfirm {{item}}"
  become: false
  when:
    - ansible_os_family == "Archlinux"
    - need_aur_software_setup == "yes"
  with_items:
    - "{{ aur_packages }}"
