---
# Enable multilib
- name: Add multilib repo
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: Add multilib mirroe
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    regexp: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"
