---
# Enable multilib
- name: Add multilib repo
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "[multilib]"
    regexp: "^\\[multilib\\]"
    insertafter: "^#\\[multilib\\]"

- name: Add multilib mirror
  lineinfile:
    dest: /etc/pacman.conf
    state: "present"
    line: "Include = /etc/pacman.d/mirrorlist"
    regexp: "Include = /etc/pacman.d/mirrorlist"
    insertafter: "^\\[multilib\\]"

- name: Install software on Arch Linux
  pacman: name={{ item }} state=latest update_cache=yes
  with_items:
    - "{{ packages }}"
